FROM nvcr.io/nvidia/pytorch:22.12-py3

WORKDIR /

RUN git clone https://github.com/MaxZabarka/vllm
RUN pip install vllm
RUN pip install -r vllm/requirements.txt
RUN pip install -e vllm
#
# RUN pip install fastapi==-2.99.1
# RUN pip install git+https://github.com/runpod/runpod-python.git@main#egg=runpod

# arg cuda_version=11.8.0
# arg cudnn_version=8
# arg ubuntu_version=22.04

# # target the cuda build image
# arg base_cuda_dev_container=nvidia/cuda:${cuda_version}-devel-ubuntu${ubuntu_version}
#
# from ${base_cuda_dev_container} as base
# FROM nvcr.io/nvidia/pytorch:22.12-py3
#
# arg aptpkgs="zsh sudo wget tmux nvtop vim neovim curl less"
# run apt-get update -y && \
#     apt-get install -y python3 python3-pip python3-venv && \
#     apt-get install -y --no-install-recommends openssh-server openssh-client git git-lfs && \
#     python3 -m pip install --upgrade pip && \
#     apt-get install -y --no-install-recommends $aptpkgs && \
#     apt-get clean && \
#     rm -rf /var/lib/apt/lists/*
#
# env path="/usr/local/cuda/bin:${path}"
#
# # env torch_cuda_arch_list="8.0;8.6+ptx;8.9;9.0"
#
# RUN git clone https://github.com/MaxZabarka/vllm
# RUN pip install -r vllm/requirements.txt
# ENV FORCE_CUDA=1
# RUN pip install -e ./vllm --verbose
#
#
# # && \
# #     cd vllm && \
# #     pip3 install -r requirements.txt && \
# #     pip3 install -e . && \
# #     # todo: remove this once error is fixed
# #     # if ray is not installed version 2.5.1, it could be cause of the following error: attributeerror: 'nonetype' object has no attribute 'fs'
# #     pip3 install ray==2.5.1 && \
#     # pip3 cache purge
#
# COPY . .
# CMD ["python3", "./src/handler.py" 
